stages:
  - build

docker-test:
  stage: build
  tags:
    - docker
  image: ubuntu:18.04
  script:
    - apt -y update
    - apt -y install cmake gcc
    - mkdir build-gcc-release
    - cd build-gcc-release
    - export CXX=g++
    - cmake -DCMAKE_BUILD_TYPE=Release ..
    - make

